services:
  api:
    image: vanjackal/combatcritters:latest
    ports:
      - "4000:8080"
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "critter_db"