services:
  api:
    image: vanjackal/combatcritters:latest
    ports:
      - "4000:8080"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    environment:
      DB_HOST: postgres:5432
      DB_USER: admin
      DB_PASS: admin
      ORIGIN: http://combatcritters.ca
      ORIGIN_DEV: http://localhost:3000
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "critter_db"
    healthcheck:
      test:  [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 120
  web:
    image: vanjackal/combatcritters-react:latest
    ports:
      - "80:3000"
    build:
      args:
        REACT_APP_API: "http://api.combatcritters.ca:4000"
      
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
