INSERT INTO PLAYERINFO VALUES (1,100);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Waffle Warrior','card_id_1',3,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Pillow Pugilist','card_id_2',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sock Samurai','card_id_3',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bubble Gum Battlers','card_id_4',3,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Tuba Trooper','card_id_5',1,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Hole-In-One Hero','card_id_6',3,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Jumpshot Soldier','card_id_7',1,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slimy Slugger','card_id_8',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Dodgeball Dragon','card_id_9',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Track and Field Titan','card_id_10',3,0,'critter',0,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Shredder Shark','card_id_11',2,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deadly Fisherman','card_id_12',3,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ambush of Anglers','card_id_13',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Airborne Guppy','card_id_14',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Conjurer of Coral','card_id_15',2,0,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Furious Fridge Fighter','card_id_17',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bubble-Wrapped Berserker','card_id_18',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Banana Barbarian','card_id_19',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Pencil Swordsman','card_id_20',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Goalkeeper Guy','card_id_21',1,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Superstriker Gal','card_id_22',3,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slapshot Beast','card_id_23',1,1,'critter',4,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Demonic Referee','card_id_24',4,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Fish Fist Fighter','card_id_25',3,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giant Carp','card_id_26',1,1,'critter',3,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Swordfish of the Samurai','card_id_27',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Heavily Armored Turtle','card_id_28',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Kitchen Knight','card_id_32',3,2,'critter',1,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giggly Gorgon, the Snickering Serpent','card_id_33',4,2,'critter',3,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Snickerdoodle Sphinx, the Grinning Guardian','card_id_34',2,2,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Surfs Up Cyborg','card_id_35',4,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Volleyball Vanguard','card_id_36',1,2,'critter',2,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slam Dunk Sorcerer','card_id_37',3,2,'critter',3,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Island Whale','card_id_38',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deep Sea Beast','card_id_39',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Barrage of Fish','card_id_40',1,2,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sweet-Toothed Dragon','card_id_47',2,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('UglyMan, the Hideous Hero','card_id_48',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Karate Boxer Man','card_id_49',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Knockout Champion','card_id_50',2,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deep Sea King','card_id_51',3,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Mega Kraken','card_id_52',3,3,'critter',5,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('White-Eyes Blue Dragon','card_id_57',2,4,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('The Sports Wizard','card_id_58',3,4,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Wrath of the Ocean','card_id_59',3,4,'critter',5,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('600 frag grenades', 'card_id_60',2,2,'item',NULL,NULL,1);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Friendship Pendant (Franklin)', 'card_id_61',3,3,'item',NULL,NULL,2);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Friendship Pendant (Rob)', 'card_id_62',3,3,'item',NULL,NULL,2);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Electric Yellow Mouse','mouse',3,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Speedy Blue Hedgehog','hedgehog',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Red European Plumber','redplumber',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Green European Plumber','greenplumber',3,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Gorilla With Necktie','gorilla',1,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giant Evil Turtle','turtle',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Wageslave Sponge','sponge',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Colorful Rangers','colorful',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Man-Spider','manspider',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Knight with Dark Soul','knight',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Psychic Cyberpunk Biker','cyberpunk',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Battle Royale Builder Man','builder',1,2,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Very Stretchy Pirate','pirate',2,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Spiky Martial Artist','monkey',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Blindfolded Albino Sorcerer','sorcerer',3,4,'critter',5,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Poutine Golem','golem',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Aurora Drake','drake',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maplewood Guardian','maple',1,0,'critter',1,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Beaver Bard','beaver',1,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ravenous Goose','goose',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Frostbitten Wendigo','wedigo',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Thunderous Caribou','thunder',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Great Lakes Leviathan','levi',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maple Syrup Monster','syrup',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rocky Mountain Raptor','raptor',3,2,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Timberwolf Alpha','wolf',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ontario Ogre','ogre',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Manitoba Mauler','manit',1,3,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Enraged Prime Minister','prime',3,4,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rob (Base Form)','normal',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('naireduG boR','reverse',2,0,'critter',3,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('ROwObert GUwUderian','cat',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Prison Realm Seal','cube',1,0,'critter',0,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bandit El Roberto','cowboy',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Violation of Principles','deepfry',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('ARCHITECTURE.md','lunch',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Samurob','samurai',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sir Guderian XVII','sir',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('The Beekeeper','bees',3,2,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('FrankMan and ROBin','batman',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Cookie Rob','cookie',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rival Professor','franklin',2,3,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('twitch.tv/robGuderian','gaming',1,3,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maximum Power Rob','roids',3,4,'critter',4,10,NULL);
INSERT INTO PACKS (name, image) VALUES('Assorted Critters','pack0');
INSERT INTO PACKS (name, image) VALUES('Athletic Assailants','pack2');
INSERT INTO PACKS (name, image) VALUES('Power of the Sea','pack1');
INSERT INTO PACKS (name, image) VALUES('Borderline Copyright Infringement','pack3');
INSERT INTO PACKS (name, image) VALUES('From the Far North','pack4');
INSERT INTO PACKS (name, image) VALUES('Into the Robverse','pack5');
INSERT INTO PACKCARDS VALUES(1,1);
INSERT INTO PACKCARDS VALUES(1,2);
INSERT INTO PACKCARDS VALUES(1,3);
INSERT INTO PACKCARDS VALUES(1,4);
INSERT INTO PACKCARDS VALUES(1,5);
INSERT INTO PACKCARDS VALUES(1,16);
INSERT INTO PACKCARDS VALUES(1,17);
INSERT INTO PACKCARDS VALUES(1,18);
INSERT INTO PACKCARDS VALUES(1,19);
INSERT INTO PACKCARDS VALUES(1,28);
INSERT INTO PACKCARDS VALUES(1,29);
INSERT INTO PACKCARDS VALUES(1,30);
INSERT INTO PACKCARDS VALUES(1,38);
INSERT INTO PACKCARDS VALUES(1,37);
INSERT INTO PACKCARDS VALUES(1,43);
INSERT INTO PACKCARDS VALUES(2,10);
INSERT INTO PACKCARDS VALUES(2,6);
INSERT INTO PACKCARDS VALUES(2,7);
INSERT INTO PACKCARDS VALUES(2,8);
INSERT INTO PACKCARDS VALUES(2,9);
INSERT INTO PACKCARDS VALUES(2,20);
INSERT INTO PACKCARDS VALUES(2,21);
INSERT INTO PACKCARDS VALUES(2,22);
INSERT INTO PACKCARDS VALUES(2,23);
INSERT INTO PACKCARDS VALUES(2,31);
INSERT INTO PACKCARDS VALUES(2,32);
INSERT INTO PACKCARDS VALUES(2,33);
INSERT INTO PACKCARDS VALUES(2,39);
INSERT INTO PACKCARDS VALUES(2,40);
INSERT INTO PACKCARDS VALUES(2,44);
INSERT INTO PACKCARDS VALUES(3,11);
INSERT INTO PACKCARDS VALUES(3,12);
INSERT INTO PACKCARDS VALUES(3,13);
INSERT INTO PACKCARDS VALUES(3,14);
INSERT INTO PACKCARDS VALUES(3,15);
INSERT INTO PACKCARDS VALUES(3,24);
INSERT INTO PACKCARDS VALUES(3,25);
INSERT INTO PACKCARDS VALUES(3,26);
INSERT INTO PACKCARDS VALUES(3,27);
INSERT INTO PACKCARDS VALUES(3,34);
INSERT INTO PACKCARDS VALUES(3,35);
INSERT INTO PACKCARDS VALUES(3,36);
INSERT INTO PACKCARDS VALUES(3,41);
INSERT INTO PACKCARDS VALUES(3,42);
INSERT INTO PACKCARDS VALUES(3,45);
INSERT INTO PACKCARDS VALUES(4,49);
INSERT INTO PACKCARDS VALUES(4,50);
INSERT INTO PACKCARDS VALUES(4,51);
INSERT INTO PACKCARDS VALUES(4,52);
INSERT INTO PACKCARDS VALUES(4,53);
INSERT INTO PACKCARDS VALUES(4,54);
INSERT INTO PACKCARDS VALUES(4,55);
INSERT INTO PACKCARDS VALUES(4,56);
INSERT INTO PACKCARDS VALUES(4,57);
INSERT INTO PACKCARDS VALUES(4,58);
INSERT INTO PACKCARDS VALUES(4,59);
INSERT INTO PACKCARDS VALUES(4,60);
INSERT INTO PACKCARDS VALUES(4,61);
INSERT INTO PACKCARDS VALUES(4,62);
INSERT INTO PACKCARDS VALUES(4,63);
INSERT INTO PACKCARDS VALUES(5,64);
INSERT INTO PACKCARDS VALUES(5,65);
INSERT INTO PACKCARDS VALUES(5,66);
INSERT INTO PACKCARDS VALUES(5,67);
INSERT INTO PACKCARDS VALUES(5,68);
INSERT INTO PACKCARDS VALUES(5,69);
INSERT INTO PACKCARDS VALUES(5,70);
INSERT INTO PACKCARDS VALUES(5,71);
INSERT INTO PACKCARDS VALUES(5,72);
INSERT INTO PACKCARDS VALUES(5,73);
INSERT INTO PACKCARDS VALUES(5,74);
INSERT INTO PACKCARDS VALUES(5,75);
INSERT INTO PACKCARDS VALUES(5,76);
INSERT INTO PACKCARDS VALUES(5,77);
INSERT INTO PACKCARDS VALUES(6,78);
INSERT INTO PACKCARDS VALUES(6,79);
INSERT INTO PACKCARDS VALUES(6,80);
INSERT INTO PACKCARDS VALUES(6,81);
INSERT INTO PACKCARDS VALUES(6,82);
INSERT INTO PACKCARDS VALUES(6,83);
INSERT INTO PACKCARDS VALUES(6,84);
INSERT INTO PACKCARDS VALUES(6,85);
INSERT INTO PACKCARDS VALUES(6,86);
INSERT INTO PACKCARDS VALUES(6,87);
INSERT INTO PACKCARDS VALUES(6,88);
INSERT INTO PACKCARDS VALUES(6,89);
INSERT INTO PACKCARDS VALUES(6,90);
INSERT INTO PACKCARDS VALUES(6,91);
INSERT INTO PACKCARDS VALUES(6,92);
INSERT INTO CARDSLOT VALUES(1,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(2,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(3,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(4,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(5,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(6,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO TRANSACTIONS VALUES(1,'m_card');
INSERT INTO TRANSACTIONS VALUES(2,'m_pack');
INSERT INTO TRANSACTIONS VALUES(3,'m_bundle');
INSERT INTO TRANSACTIONS VALUES(4,'m_card');
INSERT INTO TRANSACTIONITEM VALUES(1,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'currency','0',NULL,NULL,15,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'currency','0',NULL,NULL,30,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'currency','0',NULL,NULL,0,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'card','1',NULL,45,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(1,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,2,NULL,1);
INSERT INTO TRANSACTIONS VALUES(5,'t');
INSERT INTO TRANSACTIONS VALUES(6,'t');
INSERT INTO TRANSACTIONS VALUES(7,'t');
INSERT INTO TRANSACTIONITEM VALUES(5,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(5,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','0',NULL,44,NULL,1000);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,45,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,46,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','1',NULL,48,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','1',NULL,48,NULL,1);
INSERT INTO TRANSACTIONS VALUES(8,'m_pack');
INSERT INTO TRANSACTIONITEM VALUES(8,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(8,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONS VALUES(9,'m_pack');
INSERT INTO TRANSACTIONITEM VALUES(9,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(9,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONS VALUES(10,'m_pack');
INSERT INTO TRANSACTIONITEM VALUES(10,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(10,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONS VALUES(11,'m_pack');
INSERT INTO TRANSACTIONITEM VALUES(11,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(11,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONS VALUES(12,'m_pack');
INSERT INTO TRANSACTIONITEM VALUES(12,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(12,'pack','1',6,NULL,NULL,1);
INSERT INTO TRANSACTIONS VALUES(13,'m_bundle');
INSERT INTO TRANSACTIONITEM VALUES(13,'currency','0',NULL,NULL,50,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(5,'Trader Norman','trader4');
INSERT INTO TRADEINFO VALUES(6,'Raccoon Dealer','trader1');
INSERT INTO TRADEINFO VALUES(7,'Wise Ratman','trader2');
INSERT INTO TRANSACTIONS VALUES(14,'t');
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,20,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,11,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(14,'Shady Alley Guy','trader7');
INSERT INTO TRANSACTIONS VALUES(15,'t');
INSERT INTO TRANSACTIONITEM VALUES(15,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','0',NULL,6,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','1',NULL,24,NULL,1);
INSERT INTO TRANSACTIONS VALUES(16,'t');
INSERT INTO TRANSACTIONITEM VALUES(16,'card','0',NULL,92,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(16,'currency','1',NULL,NULL,100,1);
INSERT INTO TRADEINFO VALUES(15,'Pawn Shop Owner','trader8');
INSERT INTO TRADEINFO VALUES(16,'Card Collector','trader6');
INSERT INTO TRANSACTIONS VALUES(17, 'r');
INSERT INTO TRANSACTIONS VALUES(18, 'r');
INSERT INTO TRANSACTIONITEM VALUES(17,'card','1',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(18,'currency','1',NULL,NULL,10,1);
INSERT INTO BATTLEINFO VALUES(1, 'Norman', 'Robs Grandpa', 'card_id_59', 17);
INSERT INTO BATTLEINFO VALUES(2, 'MARGIT, THE FELL OMEN', 'Someone must extinguish thy flame. Let it be Margit the Fell!', 'card_id_51', 18);