INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Waffle Warrior','card_id_1.jpeg',3,0,'critter',1,3,NULL,'A breakfast hero armed with syrupy strength and a crispy shield, Waffle Warrior charges into battle to serve up a victory—one bite at a time!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Pillow Pugilist','card_id_2.jpeg',2,0,'critter',1,2,NULL,'Soft but scrappy, Pillow Pugilist fights with fluff and finesse, turning cozy cushions into knockout blows in the ultimate bedtime brawl!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Sock Samurai','card_id_3.jpeg',1,0,'critter',1,1,NULL,'Silent and swift, Sock Samurai wields unmatched agility and cotton-clad precision, striking foes with the fury of freshly laundered honor!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Bubble Gum Battlers','card_id_4.jpeg',3,0,'critter',0,1,NULL,'Stretching the limits of warfare, the Bubble Gum Battlers stick together, blow away enemies, and always bring a chewsy attitude to the fight!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Tuba Trooper','card_id_5.png',1,0,'critter',1,2,NULL,'Blasting foes with brass courage, the Tuba Trooper marches to the beat of its own horn, making every fight a low-blow symphony of chaos!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Hole-In-One Hero','card_id_6.jpeg',3,0,'critter',2,1,NULL,'Armed with a putter of destiny, Hole-In-One Hero swings into action, teeing up trouble and driving enemies straight into the sand trap of defeat!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Jumpshot Soldier','card_id_7.jpeg',1,0,'critter',2,1,NULL,'Jumpshot Soldier dunks on enemies with precision and flair, dribbling past danger and always taking a shot at slam-dunking victory!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Slimy Slugger','card_id_8.jpeg',2,0,'critter',1,3,NULL,'Swinging with gooey gusto, Slimy Slugger slides into battle, leaving foes stuck in their tracks and slugging out hits that are anything but slick!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Dodgeball Dragon','card_id_9.jpeg',2,0,'critter',1,2,NULL,'With fiery reflexes and a knack for dodging danger, Dodgeball Dragon hurls searing shots that leave opponents ducking and scrambling for cover!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Track and Field Titan','card_id_10.jpeg',3,0,'critter',0,2,NULL,'Blazing past the competition, Track and Field Titan hurdles obstacles, sprints to victory, and always leaves rivals eating their dust... literally!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Shredder Shark','card_id_11.jpeg',2,0,'critter',2,1,NULL,'PlacehCutting through the waves and the competition, Shredder Shark bites into battle with gnarly moves and a fin-tastic flair for destruction!older');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Deadly Fisherman','card_id_12.jpeg',3,0,'critter',1,1,NULL,'Casting lines and reeling in chaos, Deadly Fisherman hooks opponents with sharp tactics and sinks their hopes with a splash of mayhem!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Ambush of Anglers','card_id_13.jpeg',1,0,'critter',1,1,NULL,'Lurking in the depths, the Ambush of Anglers springs traps with a splash, snagging foes faster than you can say catch of the day!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Airborne Guppy','card_id_14.jpeg',1,0,'critter',1,1,NULL,'Soaring through the skies with fins of fury, Airborne Guppy proves you do not need wings to send opponents swimming for cover!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Conjurer of Coral','card_id_15.jpeg',2,0,'critter',2,3,NULL,'Weaving waves and crafting reefs, Conjurer of Coral builds barriers that leave foes between a rock and a hard place!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Furious Fridge Fighter','card_id_17.jpeg',4,1,'critter',1,1,NULL,'Cool under pressure but quick to snap, Furious Fridge Fighter shelves the competition, serving up cold cuts and frozen defeats!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Bubble-Wrapped Berserker','card_id_18.jpeg',3,1,'critter',1,3,NULL,'Popping off in every fight, Bubble-Wrapped Berserker cushions the blow for allies while making foes burst with regret!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Banana Barbarian','card_id_19.jpeg',1,1,'critter',2,4,NULL,'Peeling into battle with potassium-packed power, Banana Barbarian slips past defenses and splits enemies faster than a smoothie in a blender!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Pencil Swordsman','card_id_20.png',4,1,'critter',2,4,NULL,'Sharp and to the point, Pencil Swordsman erases doubts and rewrites the battlefield, leaving foes in a permanent state of defeat!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Goalkeeper Guy','card_id_21.jpeg',1,1,'critter',1,3,NULL,'Blocking shots and stealing glory, Goalkeeper Guy defends the net with kick-saving flair, keeping rivals stuck on the sidelines!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Superstriker Gal','card_id_22.jpeg',3,1,'critter',3,4,NULL,'Blasting past defenders with a powerful kick, Superstriker Gal bends the rules and the ball, leaving opponents flat-footed and goal-less!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Slapshot Beast','card_id_23.jpeg',1,1,'critter',4,3,NULL,'Packing a stick and a bad attitude, Slapshot Beast pounds the puck and leaves opponents quivering, wishing they could handle its shaft and fury!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Demonic Referee','card_id_24.jpeg',4,1,'critter',3,4,NULL,'Blowing whistles and breaking spirits, Demonic Referee dishes out penalties with devilish glee, ensuring no one plays fair—except it, of course!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Fish Fist Fighter','card_id_25.jpeg',3,1,'critter',3,4,NULL,'Throwing wet and wild punches, Fish Fist Fighter flops into battle, leaving foes gasping as it lays down the smack with a slippery grip!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Giant Carp','card_id_26.jpeg',1,1,'critter',3,3,NULL,'Making waves with its massive girth, Giant Carp dominates the waters, leaving foes floundering as it flexes its big, scaly muscle!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Swordfish of the Samurai','card_id_27.jpeg',1,1,'critter',2,4,NULL,'Slicing through foes with razor-sharp precision, Swordfish of the Samurai thrusts into battle, leaving enemies skewered and begging for mercy!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Heavily Armored Turtle','card_id_28.jpeg',1,1,'critter',2,4,NULL,'Slow and steady wins the brawl—Heavily Armored Turtle shrugs off blows and charges in, proving its shell is not the only thing that is hard!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Kitchen Knight','card_id_32.jpeg',3,2,'critter',1,4,NULL,'Wielding a whisk and a blade, Kitchen Knight dices, slices, and stirs up trouble, leaving foes battered, fried, and begging for seconds!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Giggly Gorgon, the Snickering Serpent','card_id_33.jpeg',4,2,'critter',3,5,NULL,'With a venomous laugh and a gaze that freezes more than hearts, Giggle Gorgon leaves enemies stiff, stuck, and questioning their life choices!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Snickerdoodle Sphinx, the Grinning Guardian','card_id_34.jpeg',2,2,'critter',2,1,NULL,'Serving riddles with a side of sass, Snickerdoodle Sphinx lures foes into sticky traps, leaving them crumbled and craving a way out!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Surfs Up Cyborg','card_id_35.jpeg',4,2,'critter',3,4,NULL,'Riding waves and shredding circuits, Surfs Up Cyborg carves through foes with high-voltage moves, leaving them wiped out and short-circuited!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Volleyball Vanguard','card_id_36.jpeg',1,2,'critter',2,5,NULL,'Spiking with precision and serving up pain, Volleyball Vanguard sets the stage for victory while leaving foes begging for a time-out!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Slam Dunk Sorcerer','card_id_37.png',3,2,'critter',3,3,NULL,'Casting spells and throwing down dunks, Slam Dunk Sorcerer enchants the court, leaving opponents bewitched, blocked, and utterly dunked on!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Island Whale','card_id_38.jpeg',3,2,'critter',1,3,NULL,'Making waves with its massive presence, Island Whale crushes foes under its weight, proving size matters when you bring the ocean to battle!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Deep Sea Beast','card_id_39.jpeg',2,2,'critter',3,4,NULL,'Lurking in the depths, Deep Sea Beast rises to crush its prey, dragging them down where the pressure is high, and escape is impossible!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Barrage of Fish','card_id_40.jpeg',1,2,'critter',2,3,NULL,'A flurry of fins and scales, Barrage of Fish overwhelms foes with a wet, wild assault, leaving them gasping for breath and dignity!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Sweet-Toothed Dragon','card_id_47.jpeg',2,3,'critter',4,6,NULL,'Craving candy and crushing enemies, Sweet-Toothed Dragon melts hearts and defenses, leaving foes stuck in a sticky, sugary nightmare!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('UglyMan, the Hideous Hero','card_id_48.jpeg',3,3,'critter',4,5,NULL,'UglyMan charges into battle with a face only danger could love, leaving foes stunned, scarred, and questioning their life choices!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Karate Boxer Man','card_id_49.jpeg',3,3,'critter',4,5,NULL,'With fists of fury and kicks that hit harder than reality, Karate Boxer Man strikes low, high, and wherever it hurts most!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Knockout Champion','card_id_50.jpeg',2,3,'critter',4,5,NULL,'Swinging with precision and landing hits that echo, Knockout Champion floors foes faster than their excuses for being in the ring!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Deep Sea King','card_id_51.jpeg',3,3,'critter',4,6,NULL,'Ruling the depths with an iron fin, Deep Sea King crushes challengers under waves of raw power, leaving them drowning in regret!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Mega Kraken','card_id_52.jpeg',3,3,'critter',5,6,NULL,'Unleashing tentacles of terror, Mega Kraken drags enemies into the depths, squeezing out hope and leaving nothing but bubbles behind!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('White-Eyes Blue Dragon','card_id_57.jpeg',2,4,'critter',4,5,NULL,'With icy breath and piercing gaze, White-Eyes Blue Dragon freezes the battlefield, leaving foes chilled to the bone and begging for mercy!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('The Sports Wizard','card_id_58.jpeg',3,4,'critter',4,6,NULL,'Casting spells with a whistle and a playbook, The Sports Wizard dribbles, spikes, and scores while leaving opponents benched and bewildered!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Wrath of the Ocean','card_id_59.jpeg',3,4,'critter',5,5,NULL,'Unleashing tidal fury, Wrath of the Ocean crashes into battle, drowning foes in waves of destruction and watery regret!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('600 frag grenades', 'card_id_60.png',3,2,'critter',6,1,null,'Packing enough destructive force to shatter the codebase and morale, 600 frag grenades turned a simple commit into a catastrophic detonation!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Friendship Pendant (Franklin)', 'card_id_61.jpg',3,3,'critter',3,5,null,'Infused with Franklin power, the Friendship Pendant strikes a balance between wisdom and chaos, leaving allies enlightened and enemies bewildered!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Friendship Pendant (Rob)', 'card_id_62.jpg',3,3,'critter',3,5,null,'Forged in the fires of academia, the Friendship Pendant channels Robs power to inspire or crush with a single soul-piercing lecture of doom!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Electric Yellow Mouse','mouse.jpg',3,0,'critter',1,3,NULL,'Buzzing with high voltage and boundless energy, Electric Yellow Mouse electrifies the battlefield, sparking chaos and lighting up the competition!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Speedy Blue Hedgehog','hedgehog.jpg',2,0,'critter',1,2,NULL,'Blazing past the competition, Speedy Blue Hedgehog spins into action, leaving nothing but a trail of dust and a whole lot of attitude!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Red European Plumber','redplumber.jpg',1,0,'critter',1,1,NULL,'Jumping headfirst into chaos, Red European Plumber lays the groundwork for victory, stomping problems flat and piping up when it matters most!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Green European Plumber','greenplumber.jpg',3,0,'critter',0,1,NULL,'Always in his brothers shadow, Green European Plumber leaps into action with quiet determination and a pipe full of surprising moves!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Gorilla With Necktie','gorilla.jpg',1,0,'critter',1,2,NULL,'Swinging through the jungle of legal loopholes, Gorilla with Necktie barrels into battle, smashing foes and bananas with unlicensed style!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Giant Evil Turtle','turtle.jpg',4,1,'critter',1,1,NULL,'Emerging from murky waters of plausible deniability, Giant Evil Turtle crushes the competition under its shell of totally original chaos!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Wageslave Sponge','sponge.jpg',3,1,'critter',1,3,NULL,'Soaked in sweat from endless shifts under a penny-pinching crab, Wageslave Sponge flips foes and patties with a smile as fake as fair use!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Colorful Rangers','colorful.jpg',1,1,'critter',2,4,NULL,'Clad in vibrant suits and synchronized poses, the Colorful Rangers summon their mega-sized teamwork to outmaneuver any foe and save the day!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Man-Spider','manspider.jpg',4,1,'critter',2,4,NULL,'Crawling through the shadows with eight legs of trouble, Man-Spider spins webs of chaos and sticks it to anyone who dares cross his path!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Knight with Dark Soul','knight.jpg',3,2,'critter',1,3,NULL,'Wielding a sword forged in the depths of despair, Knight with Dark Soul charges into battle, slicing through light and leaving a trail of shadows in his wake!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Psychic Cyberpunk Biker','cyberpunk.jpg',2,2,'critter',3,4,NULL,'Revving up the future with neon energy, Psychic Cyberpunk Biker teleports through chaos, leaving a trail of sparks and psychic blasts that hit harder than his ride!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Battle Royale Builder Man','builder.jpg',1,2,'critter',2,3,NULL,'Building chaos brick by brick, Battle Royale Builder Man constructs traps, walls, and victories, leaving foes tangled in his web of strategic destruction!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Very Stretchy Pirate','pirate.jpg',2,3,'critter',4,6,NULL,'Stretching the limits of adventure, Very Stretchy Pirate swings from ship to ship, reaching new heights of chaos while stealing treasure and sanity!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Spiky Martial Artist','monkey.jpg',3,3,'critter',4,5,NULL,'With every kick sharper than his attitude, Spiky Martial Artist pricks anyone who gets too close, leaving foes bruised, bent, and stuck in his web of pain!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Blindfolded Albino Sorcerer','sorcerer.jpg',3,4,'critter',5,5,NULL,'Casting spells with zero sight and all the sass, Blindfolded Albino Sorcerer hits enemies with magic so wild, they won’t know what hit them—literally!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Poutine Golem','golem.jpeg',2,0,'critter',1,3,NULL,'Made of gravy, cheese, and all the bad decisions, Poutine Golem stomps through the battlefield, leaving enemies soggy, defeated, and covered in cheesy chaos!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Aurora Drake','drake.jpeg',2,0,'critter',1,2,NULL,'With scales that shimmer like a northern light, Aurora Drake glides through battle, freezing enemies in place and leaving them cold, stunned, and craving warmth!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Maplewood Guardian','maple.jpeg',1,0,'critter',1,4,NULL,'Rooted in strength and covered in sap, Maplewood Guardian shields the battlefield, sticking enemies in place and leaving them tree-mendously stuck!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Beaver Bard','beaver.jpeg',1,0,'critter',0,1,NULL,'Strumming his axe and building bridges with tunes, Beaver Bard leaves foes floored by his catchy jams and sharp wooden hits.');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Ravenous Goose','goose.png',2,0,'critter',1,2,NULL,'With a honk of hunger and a peck of fury, Ravenous Goose devours everything in its path, leaving nothing but chaos and a trail of feathers behind!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Frostbitten Wendigo','wedigo.jpeg',4,1,'critter',1,1,NULL,'Hungry for more than just fear, Frostbitten Wendigo stalks the cold, freezing foes in their tracks and feasting on their frozen screams!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Thunderous Caribou','thunder.jpeg',3,1,'critter',1,3,NULL,'Charging through storms with hooves of thunder, Thunderous Caribou strikes fear into enemies, leaving them shaken and electrified by its mighty charge!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Great Lakes Leviathan','levi.jpeg',1,1,'critter',2,4,NULL,'Rising from the deep with monstrous might, Great Lakes Leviathan crashes through waters, dragging foes down into its cold, murky depths!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Maple Syrup Monster','syrup.jpeg',4,1,'critter',2,4,NULL,'Sticky, sweet, and absolutely terrifying, Maple Syrup Monster oozes through the battlefield, trapping foes in a sugary mess they can’t escape!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Rocky Mountain Raptor','raptor.jpeg',3,2,'critter',2,4,NULL,'Soaring through the peaks with deadly precision, Rocky Mountain Raptor swoops down, striking hard and leaving its mark on the competition!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Timberwolf Alpha','wolf.jpeg',3,2,'critter',1,3,NULL,'Leading the pack with fierce loyalty and razor-sharp claws, Timberwolf Alpha dominates the battlefield, hunting down foes with savage precision!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Ontario Ogre','ogre.jpeg',2,2,'critter',3,4,NULL,'Lumbering through the land with a gruff growl, Ontario Ogre smashes foes with boulders and brute strength, leaving a trail of wreckage and crushed pride!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Manitoba Mauler','manit.jpeg',1,3,'critter',2,3,NULL,'Charging through the snow with bone-crushing force, Manitoba Mauler tears through enemies, leaving nothing but destruction and frozen regrets in its wake!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Enraged Prime Minister','prime.jpeg',3,4,'critter',4,5,NULL,'Raging with unchecked power, Enraged Prime Minister storms the battlefield, making bold moves and crushing opposition with policies of pure chaos!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Rob (Base Form)','normal.png',2,0,'critter',1,3,NULL,'Your internet friend.');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('naireduG boR','reverse.png',2,0,'critter',3,1,NULL,'dneirf tenretni ruoy.');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('ROwObert GUwUderian','cat.png',1,0,'critter',1,1,NULL,'ROwObert GUwUderian enters with a flair for dramatic confusion, blending uwu charm with the power to make you question your entire existence—squee, or maybe scream!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Prison Realm Seal','cube.gif',1,0,'critter',0,5,NULL,'Prison Realm Seal traps enemies in a dimension of pure chaos, sealing their fate with unrelenting power and a tight grip that no one can escape!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Bandit El Roberto','cowboy.png',2,0,'critter',1,2,NULL,'Bandit El Roberto rides in with a dusty hat and a devil-may-care attitude, ready to rob your sanity and your grade with quick-witted gunfire and questionable decisions!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Violation of Principles','deepfry.png',4,1,'critter',1,1,NULL,'Violation of Principles takes SOLID and bends it over, leaving a messy, chaotic codebase that’s violated beyond recognition—no structure, no mercy, just pure anarchy!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('ARCHITECTURE.md','lunch.png',3,1,'critter',1,3,NULL,'ARCHITECTURE.md: A spaghetti diagram so tangled, no one will ever understand it—each line a confusing twist, leaving you lost in the sauce of pure chaos!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Samurob','samurai.png',1,1,'critter',2,4,NULL,'Samurob, once a professor, now a samurai, grades with a katana and honor, slashing mistakes and leaving nothing but red marks and broken spirits.');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Sir Guderian XVII','sir.png',4,1,'critter',2,4,NULL,'Sir Guderian XVII rides in with regal flair, ready to knight your grades with unquestionable authority and a well-placed sigh of disappointment.');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('The Beekeeper','bees.png',3,2,'critter',2,4,NULL,'The Beekeeper tends his hive with ruthless precision, making honey and buzzing with anger when things don’t go his way—dont get too close!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('FrankMan and ROBin','batman.png',3,2,'critter',1,3,NULL,'FrankMan and ROBin, the dynamic duo, fight crime with brains and questionable teamwork—FrankMan lectures, while ROBin grades with a vengeance!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Cookie Rob','cookie.png',3,2,'critter',1,3,NULL,'Cookie Rob taps his way to victory, baking up a storm of sweet distractions while secretly calculating how to optimize his cookie empire!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Rival Professor','franklin.png',2,3,'critter',3,4,NULL,'Rival Professor enters with a smug grin, armed with unshakable confidence, ready to outsmart Rob and leave everyone questioning their grades!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('twitch.tv/robGuderian','gaming.png',1,3,'critter',2,3,NULL,'Join Rob at twitch.tv/robGuderian and become his internet friend... or else. Don’t test him—he’s got knowledge, a mic, and way too much time on his hands!');
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid, description) VALUES ('Maximum Power Rob','roids.png',3,4,'critter',4,10,NULL,'Maximum Power Rob flexes his muscles and intellect, shirtless and unstoppable, ready to dominate anything that dares stand in his way—brace yourself!');
INSERT INTO PACKS (name, image) VALUES('Assorted Critters','pack0.png');
INSERT INTO PACKS (name, image) VALUES('Athletic Assailants','pack2.png');
INSERT INTO PACKS (name, image) VALUES('Power of the Sea','pack1.png');
INSERT INTO PACKS (name, image) VALUES('"Fair Use"','pack3.png');
INSERT INTO PACKS (name, image) VALUES('From the Far North','pack4.png');
INSERT INTO PACKS (name, image) VALUES('Into the Robverse','pack5.png');
INSERT INTO PACKCARDS VALUES(1,1);
INSERT INTO PACKCARDS VALUES(1,2);
INSERT INTO PACKCARDS VALUES(1,3);
INSERT INTO PACKCARDS VALUES(1,4);
INSERT INTO PACKCARDS VALUES(1,5);
INSERT INTO PACKCARDS VALUES(1,16);
INSERT INTO PACKCARDS VALUES(1,17);
INSERT INTO PACKCARDS VALUES(1,18);
INSERT INTO PACKCARDS VALUES(1,19);
INSERT INTO PACKCARDS VALUES(1,28);
INSERT INTO PACKCARDS VALUES(1,29);
INSERT INTO PACKCARDS VALUES(1,30);
INSERT INTO PACKCARDS VALUES(1,38);
INSERT INTO PACKCARDS VALUES(1,37);
INSERT INTO PACKCARDS VALUES(1,43);
INSERT INTO PACKCARDS VALUES(2,10);
INSERT INTO PACKCARDS VALUES(2,6);
INSERT INTO PACKCARDS VALUES(2,7);
INSERT INTO PACKCARDS VALUES(2,8);
INSERT INTO PACKCARDS VALUES(2,9);
INSERT INTO PACKCARDS VALUES(2,20);
INSERT INTO PACKCARDS VALUES(2,21);
INSERT INTO PACKCARDS VALUES(2,22);
INSERT INTO PACKCARDS VALUES(2,23);
INSERT INTO PACKCARDS VALUES(2,31);
INSERT INTO PACKCARDS VALUES(2,32);
INSERT INTO PACKCARDS VALUES(2,33);
INSERT INTO PACKCARDS VALUES(2,39);
INSERT INTO PACKCARDS VALUES(2,40);
INSERT INTO PACKCARDS VALUES(2,44);
INSERT INTO PACKCARDS VALUES(3,11);
INSERT INTO PACKCARDS VALUES(3,12);
INSERT INTO PACKCARDS VALUES(3,13);
INSERT INTO PACKCARDS VALUES(3,14);
INSERT INTO PACKCARDS VALUES(3,15);
INSERT INTO PACKCARDS VALUES(3,24);
INSERT INTO PACKCARDS VALUES(3,25);
INSERT INTO PACKCARDS VALUES(3,26);
INSERT INTO PACKCARDS VALUES(3,27);
INSERT INTO PACKCARDS VALUES(3,34);
INSERT INTO PACKCARDS VALUES(3,35);
INSERT INTO PACKCARDS VALUES(3,36);
INSERT INTO PACKCARDS VALUES(3,41);
INSERT INTO PACKCARDS VALUES(3,42);
INSERT INTO PACKCARDS VALUES(3,45);
INSERT INTO PACKCARDS VALUES(4,49);
INSERT INTO PACKCARDS VALUES(4,50);
INSERT INTO PACKCARDS VALUES(4,51);
INSERT INTO PACKCARDS VALUES(4,52);
INSERT INTO PACKCARDS VALUES(4,53);
INSERT INTO PACKCARDS VALUES(4,54);
INSERT INTO PACKCARDS VALUES(4,55);
INSERT INTO PACKCARDS VALUES(4,56);
INSERT INTO PACKCARDS VALUES(4,57);
INSERT INTO PACKCARDS VALUES(4,58);
INSERT INTO PACKCARDS VALUES(4,59);
INSERT INTO PACKCARDS VALUES(4,60);
INSERT INTO PACKCARDS VALUES(4,61);
INSERT INTO PACKCARDS VALUES(4,62);
INSERT INTO PACKCARDS VALUES(4,63);
INSERT INTO PACKCARDS VALUES(5,64);
INSERT INTO PACKCARDS VALUES(5,65);
INSERT INTO PACKCARDS VALUES(5,66);
INSERT INTO PACKCARDS VALUES(5,67);
INSERT INTO PACKCARDS VALUES(5,68);
INSERT INTO PACKCARDS VALUES(5,69);
INSERT INTO PACKCARDS VALUES(5,70);
INSERT INTO PACKCARDS VALUES(5,71);
INSERT INTO PACKCARDS VALUES(5,72);
INSERT INTO PACKCARDS VALUES(5,73);
INSERT INTO PACKCARDS VALUES(5,74);
INSERT INTO PACKCARDS VALUES(5,75);
INSERT INTO PACKCARDS VALUES(5,76);
INSERT INTO PACKCARDS VALUES(5,77);
INSERT INTO PACKCARDS VALUES(6,78);
INSERT INTO PACKCARDS VALUES(6,79);
INSERT INTO PACKCARDS VALUES(6,80);
INSERT INTO PACKCARDS VALUES(6,81);
INSERT INTO PACKCARDS VALUES(6,82);
INSERT INTO PACKCARDS VALUES(6,83);
INSERT INTO PACKCARDS VALUES(6,84);
INSERT INTO PACKCARDS VALUES(6,85);
INSERT INTO PACKCARDS VALUES(6,86);
INSERT INTO PACKCARDS VALUES(6,87);
INSERT INTO PACKCARDS VALUES(6,88);
INSERT INTO PACKCARDS VALUES(6,89);
INSERT INTO PACKCARDS VALUES(6,90);
INSERT INTO PACKCARDS VALUES(6,91);
INSERT INTO PACKCARDS VALUES(6,92);
INSERT INTO CARDSLOT VALUES(1,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(2,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(3,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(4,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(5,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(6,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO TRANSACTIONS (type) VALUES('m_card');
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONS (type) VALUES('m_bundle');
INSERT INTO TRANSACTIONS (type) VALUES('m_card');
INSERT INTO TRANSACTIONITEM VALUES(1,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'currency','0',NULL,NULL,15,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'currency','0',NULL,NULL,30,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'currency','0',NULL,NULL,0,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'card','1',NULL,45,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(1,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,2,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(5,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(5,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','0',NULL,44,NULL,1000);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,45,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,46,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','1',NULL,48,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','1',NULL,48,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(8,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(8,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(9,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(9,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(10,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(10,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(11,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(11,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(12,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(12,'pack','1',6,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_bundle');
INSERT INTO TRANSACTIONITEM VALUES(13,'currency','0',NULL,NULL,50,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(5,'Trader Norman','trader4');
INSERT INTO TRADEINFO VALUES(6,'Raccoon Dealer','trader1');
INSERT INTO TRADEINFO VALUES(7,'Wise Ratman','trader2');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,20,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,11,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(14,'Shady Alley Guy','trader7');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(15,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','0',NULL,6,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','1',NULL,24,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(16,'card','0',NULL,92,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(16,'currency','1',NULL,NULL,100,1);
INSERT INTO TRADEINFO VALUES(15,'Pawn Shop Owner','trader8');
INSERT INTO TRADEINFO VALUES(16,'Card Collector','trader6');
INSERT INTO TRANSACTIONS (type) VALUES( 'r');
INSERT INTO TRANSACTIONS (type) VALUES( 'r');
INSERT INTO TRANSACTIONITEM VALUES(17,'card','1',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(18,'currency','1',NULL,NULL,10,1);
INSERT INTO BATTLEINFO VALUES(1, 'Norman', 'Robs Grandpa', 'card_id_59', 17);
INSERT INTO BATTLEINFO VALUES(2, 'MARGIT, THE FELL OMEN', 'Someone must extinguish thy flame. Let it be Margit the Fell!', 'card_id_51', 18);
-- Vendors
INSERT INTO VENDORS (name, image, refresh) VALUES ('Dave', 'vendor_1.webp',60);
INSERT INTO VENDORS (name, image, refresh) VALUES ('Sketch', 'vendor_0.jpg',3600);
INSERT INTO VENDORS (name, image, refresh) VALUES ('just some guy', 'vendor_2.webp',3600);
INSERT INTO VENDORS (name, image, refresh) VALUES ('Roberto', 'vendor_roberto.png',3600);

-- Roberto
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(19,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(19,'card','1',NULL,24,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 19, 0);
INSERT INTO StandardOffers Values(19);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(20,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(20,'card','1',NULL,5,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 20, 1);
INSERT INTO StandardOffers Values(20);
-- Money Printer
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES(2, 21, 0);
INSERT INTO StandardOffers Values(21);
INSERT INTO TRANSACTIONITEM VALUES(21,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(21,'currency','1',NULL,NULL,100,1);

-- Packs
INSERT INTO VENDOROFFERS VALUES (3,8,0);
INSERT INTO VENDOROFFERS VALUES (3,9,1);
INSERT INTO VENDOROFFERS VALUES (3,10,1);
INSERT INTO VENDOROFFERS VALUES (3,11,2);
INSERT INTO VENDOROFFERS VALUES (3,12,3);
INSERT INTO StandardOffers Values(8);
INSERT INTO StandardOffers Values(9);
INSERT INTO StandardOffers Values(10);
INSERT INTO StandardOffers Values(11);
INSERT INTO StandardOffers Values(12);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (3,22,4);
INSERT INTO StandardOffers Values(22);
INSERT INTO TRANSACTIONITEM VALUES(22,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(22,'card','0',NULL,24,NULL,3);
INSERT INTO TRANSACTIONITEM VALUES(22,'pack','1',6,NULL,NULL,3);
-- Rob Cards
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,23,3);
INSERT INTO StandardOffers Values(23);
INSERT INTO TRANSACTIONITEM VALUES(23,'currency','0',NULL,NULL,20,1);
INSERT INTO TRANSACTIONITEM VALUES(23,'card','1',NULL,48,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,24,0);
INSERT INTO StandardOffers Values(24);
INSERT INTO TRANSACTIONITEM VALUES(24,'currency','0',NULL,NULL,120,1);
INSERT INTO TRANSACTIONITEM VALUES(24,'card','1',NULL,89,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,25,1);
INSERT INTO StandardOffers Values(25);
INSERT INTO TRANSACTIONITEM VALUES(25,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(25,'card','1',NULL,85,NULL,3);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,26,2);
INSERT INTO StandardOffers Values(26);
INSERT INTO TRANSACTIONITEM VALUES(26,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(26,'card','1',NULL,87,NULL,3);
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,27,2);
INSERT INTO StandardOffers Values(27);
INSERT INTO TRANSACTIONITEM VALUES(27,'card','0',NULL,80,NULL,15);
INSERT INTO TRANSACTIONITEM VALUES(27,'card','1',NULL,92,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,28,1);
INSERT INTO SpecialOffers Values(28, true);
INSERT INTO TRANSACTIONITEM VALUES(28,'currency','0',NULL,NULL,14,1);
INSERT INTO TRANSACTIONITEM VALUES(28,'card','1',NULL,80,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,29,1);
INSERT INTO DiscountOffers Values(29, 28, 50);
INSERT INTO TRANSACTIONITEM VALUES(29,'currency','0',NULL,NULL,7,1);
INSERT INTO TRANSACTIONITEM VALUES(29,'card','1',NULL,80,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(30,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(30,'card','1',NULL,10,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 30, 0);
INSERT INTO StandardOffers Values(30);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(31,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(31,'card','1',NULL,10,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 31, 0);
INSERT INTO DiscountOffers Values(31,30,50);

-- Money printer ++
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES(2, 32, 0);
INSERT INTO StandardOffers Values(32);
INSERT INTO TRANSACTIONITEM VALUES(32,'currency','0',NULL,NULL,100,1);
INSERT INTO TRANSACTIONITEM VALUES(32,'currency','1',NULL,NULL,1000,1);

INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (3,33,0);
INSERT INTO SpecialOffers VALUES(33, false);
INSERT INTO TransactionItem VALUES(33,'currency','0',NULL,NULL,10,1);
INSERT INTO TransactionItem VALUES(33,'pack','1',1,NULL,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (3,34,0);
INSERT INTO SpecialOffers VALUES(34, false);
INSERT INTO TransactionItem VALUES(34,'currency','0',NULL,NULL,10,1);
INSERT INTO TransactionItem VALUES(34,'pack','0',1,NULL,NULL,1);
INSERT INTO TransactionItem VALUES(34,'pack','1',6,NULL,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,35,0);
INSERT INTO StandardOffers VALUES (35);
INSERT INTO TransactionItem VALUES(35,'currency','0',NULL,NULL,30,1);
INSERT INTO TransactionItem VALUES(35,'card','1',NULL,65,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,36,0);
INSERT INTO StandardOffers VALUES (36);
INSERT INTO TransactionItem VALUES(36,'currency','0',NULL,NULL,15,1);
INSERT INTO TransactionItem VALUES(36,'card','1',NULL,67,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,37,0);
INSERT INTO StandardOffers VALUES (37);
INSERT INTO TransactionItem VALUES(37,'currency','0',NULL,NULL,50,1);
INSERT INTO TransactionItem VALUES(37,'card','1',NULL,18,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,38,0);
INSERT INTO StandardOffers VALUES (38);
INSERT INTO TransactionItem VALUES(38,'card','0',NULL,13,NULL,2);
INSERT INTO TransactionItem VALUES(38,'card','0',NULL,68,NULL,1);
INSERT INTO TransactionItem VALUES(38,'card','1',NULL,27,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,39,0);
INSERT INTO SpecialOffers VALUES(39, false);
INSERT INTO TransactionItem VALUES(39,'currency','0',NULL,NULL,55,1);
INSERT INTO TransactionItem VALUES(39,'card','1',NULL,60,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,40,1);
INSERT INTO StandardOffers VALUES (40);
INSERT INTO TransactionItem VALUES(40,'currency','0',NULL,NULL,48,1);
INSERT INTO TransactionItem VALUES(40,'card','1',NULL,23,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,41,1);
INSERT INTO StandardOffers VALUES (41);
INSERT INTO TransactionItem VALUES(41,'currency','0',NULL,NULL,75,1);
INSERT INTO TransactionItem VALUES(41,'card','1',NULL,36,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,42,1);
INSERT INTO StandardOffers VALUES (42);
INSERT INTO TransactionItem VALUES(42,'currency','0',NULL,NULL,65,1);
INSERT INTO TransactionItem VALUES(42,'card','1',NULL,34,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,43,1);
INSERT INTO StandardOffers VALUES (43);
INSERT INTO TransactionItem VALUES(43,'card','0',NULL,65,NULL,1);
INSERT INTO TransactionItem VALUES(43,'card','0',NULL,4,NULL,1);
INSERT INTO TransactionItem VALUES(43,'card','0',NULL,55,NULL,1);
INSERT INTO TransactionItem VALUES(43,'card','1',NULL,37,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,44,0);
INSERT INTO SpecialOffers VALUES(44, false);
INSERT INTO TransactionItem VALUES(44,'currency','0',NULL,NULL,250,1);
INSERT INTO TransactionItem VALUES(44,'card','1',NULL,43,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (1,45,0);
INSERT INTO SpecialOffers VALUES(45, false);
INSERT INTO TransactionItem VALUES(45,'currency','0',NULL,NULL,150,1);
INSERT INTO TransactionItem VALUES(45,'card','1',NULL,46,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,46,0);
INSERT INTO StandardOffers VALUES (46);
INSERT INTO TransactionItem VALUES(46,'currency','0',NULL,NULL,32,1);
INSERT INTO TransactionItem VALUES(46,'card','1',NULL,78,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,47,0);
INSERT INTO StandardOffers VALUES (47);
INSERT INTO TransactionItem VALUES(47,'currency','0',NULL,NULL,23,1);
INSERT INTO TransactionItem VALUES(47,'card','1',NULL,79,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,48,0);
INSERT INTO StandardOffers VALUES (48);
INSERT INTO TransactionItem VALUES(48,'currency','0',NULL,NULL,52,1);
INSERT INTO TransactionItem VALUES(48,'card','1',NULL,82,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,49,0);
INSERT INTO StandardOffers VALUES (49);
INSERT INTO TransactionItem VALUES(49,'card','0',NULL,78,NULL,1);
INSERT INTO TransactionItem VALUES(49,'card','0',NULL,3,NULL,1);
INSERT INTO TransactionItem VALUES(49,'card','1',NULL,85,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,50,0);
INSERT INTO SpecialOffers VALUES(50, false);
INSERT INTO TransactionItem VALUES(50,'card','0',NULL,79,NULL,1);
INSERT INTO TransactionItem VALUES(50,'card','0',NULL,46,NULL,1);
INSERT INTO TransactionItem VALUES(50,'card','1',NULL,83,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,51,1);
INSERT INTO StandardOffers VALUES (51);
INSERT INTO TransactionItem VALUES(51,'currency','0',NULL,NULL,90,1);
INSERT INTO TransactionItem VALUES(51,'card','1',NULL,84,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,52,1);
INSERT INTO StandardOffers VALUES (52);
INSERT INTO TransactionItem VALUES(52,'currency','0',NULL,NULL,111,1);
INSERT INTO TransactionItem VALUES(52,'card','1',NULL,88,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,53,1);
INSERT INTO StandardOffers VALUES (53);
INSERT INTO TransactionItem VALUES(53,'card','0',NULL,81,NULL,1);
INSERT INTO TransactionItem VALUES(53,'card','0',NULL,72,NULL,1);
INSERT INTO TransactionItem VALUES(53,'card','1',NULL,87,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,54,0);
INSERT INTO SpecialOffers VALUES(54, false);
INSERT INTO TransactionItem VALUES(54,'currency','0',NULL,NULL,242,1);
INSERT INTO TransactionItem VALUES(54,'card','1',NULL,91,NULL,1);
INSERT INTO Transactions (type) VALUES('t');
INSERT INTO VendorOffers VALUES (4,55,0);
INSERT INTO SpecialOffers VALUES(55, false);
INSERT INTO TransactionItem VALUES(55,'card','0',NULL,78,NULL,1);
INSERT INTO TransactionItem VALUES(55,'card','0',NULL,1,NULL,1);
INSERT INTO TransactionItem VALUES(55,'card','1',NULL,86,NULL,1);