INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Waffle Warrior','card_id_1.jpeg',3,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Pillow Pugilist','card_id_2.jpeg',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sock Samurai','card_id_3.jpeg',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bubble Gum Battlers','card_id_4.jpeg',3,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Tuba Trooper','card_id_5.png',1,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Hole-In-One Hero','card_id_6.jpeg',3,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Jumpshot Soldier','card_id_7.jpeg',1,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slimy Slugger','card_id_8.jpeg',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Dodgeball Dragon','card_id_9.jpeg',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Track and Field Titan','card_id_10.jpeg',3,0,'critter',0,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Shredder Shark','card_id_11.jpeg',2,0,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deadly Fisherman','card_id_12.jpeg',3,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ambush of Anglers','card_id_13.jpeg',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Airborne Guppy','card_id_14.jpeg',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Conjurer of Coral','card_id_15.jpeg',2,0,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Furious Fridge Fighter','card_id_17.jpeg',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bubble-Wrapped Berserker','card_id_18.jpeg',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Banana Barbarian','card_id_19.jpeg',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Pencil Swordsman','card_id_20.png',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Goalkeeper Guy','card_id_21.jpeg',1,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Superstriker Gal','card_id_22.jpeg',3,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slapshot Beast','card_id_23.jpeg',1,1,'critter',4,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Demonic Referee','card_id_24.jpeg',4,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Fish Fist Fighter','card_id_25.jpeg',3,1,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giant Carp','card_id_26.jpeg',1,1,'critter',3,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Swordfish of the Samurai','card_id_27.jpeg',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Heavily Armored Turtle','card_id_28.jpeg',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Kitchen Knight','card_id_32.jpeg',3,2,'critter',1,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giggly Gorgon, the Snickering Serpent','card_id_33.jpeg',4,2,'critter',3,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Snickerdoodle Sphinx, the Grinning Guardian','card_id_34.jpeg',2,2,'critter',2,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Surfs Up Cyborg','card_id_35.jpeg',4,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Volleyball Vanguard','card_id_36.jpeg',1,2,'critter',2,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Slam Dunk Sorcerer','card_id_37.png',3,2,'critter',3,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Island Whale','card_id_38.jpeg',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deep Sea Beast','card_id_39.jpeg',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Barrage of Fish','card_id_40.jpeg',1,2,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sweet-Toothed Dragon','card_id_47.jpeg',2,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('UglyMan, the Hideous Hero','card_id_48.jpeg',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Karate Boxer Man','card_id_49.jpeg',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Knockout Champion','card_id_50.jpeg',2,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Deep Sea King','card_id_51.jpeg',3,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Mega Kraken','card_id_52.jpeg',3,3,'critter',5,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('White-Eyes Blue Dragon','card_id_57.jpeg',2,4,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('The Sports Wizard','card_id_58.jpeg',3,4,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Wrath of the Ocean','card_id_59.jpeg',3,4,'critter',5,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('600 frag grenades', 'card_id_60.png',2,2,'item',NULL,NULL,1);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Friendship Pendant (Franklin)', 'card_id_61.jpg',3,3,'item',NULL,NULL,2);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Friendship Pendant (Rob)', 'card_id_62.jpg',3,3,'item',NULL,NULL,2);;
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Electric Yellow Mouse','mouse.jpg',3,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Speedy Blue Hedgehog','hedgehog.jpg',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Red European Plumber','redplumber.jpg',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Green European Plumber','greenplumber.jpg',3,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Gorilla With Necktie','gorilla.jpg',1,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Giant Evil Turtle','turtle.jpg',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Wageslave Sponge','sponge.jpg',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Colorful Rangers','colorful.jpg',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Man-Spider','manspider.jpg',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Knight with Dark Soul','knight.jpg',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Psychic Cyberpunk Biker','cyberpunk.jpg',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Battle Royale Builder Man','builder.jpg',1,2,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Very Stretchy Pirate','pirate.jpg',2,3,'critter',4,6,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Spiky Martial Artist','monkey.jpg',3,3,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Blindfolded Albino Sorcerer','sorcerer.jpg',3,4,'critter',5,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Poutine Golem','golem.jpeg',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Aurora Drake','drake.jpeg',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maplewood Guardian','maple.jpeg',1,0,'critter',1,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Beaver Bard','beaver.jpeg',1,0,'critter',0,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ravenous Goose','goose.png',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Frostbitten Wendigo','wedigo.jpeg',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Thunderous Caribou','thunder.jpeg',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Great Lakes Leviathan','levi.jpeg',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maple Syrup Monster','syrup.jpeg',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rocky Mountain Raptor','raptor.jpeg',3,2,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Timberwolf Alpha','wolf.jpeg',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Ontario Ogre','ogre.jpeg',2,2,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Manitoba Mauler','manit.jpeg',1,3,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Enraged Prime Minister','prime.jpeg',3,4,'critter',4,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rob (Base Form)','normal.png',2,0,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('naireduG boR','reverse.png',2,0,'critter',3,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('ROwObert GUwUderian','cat.png',1,0,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Prison Realm Seal','cube.png',1,0,'critter',0,5,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Bandit El Roberto','cowboy.png',2,0,'critter',1,2,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Violation of Principles','deepfry.png',4,1,'critter',1,1,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('ARCHITECTURE.md','lunch.png',3,1,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Samurob','samurai.png',1,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Sir Guderian XVII','sir.png',4,1,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('The Beekeeper','bees.png',3,2,'critter',2,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('FrankMan and ROBin','batman.png',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Cookie Rob','cookie.png',3,2,'critter',1,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Rival Professor','franklin.png',2,3,'critter',3,4,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('twitch.tv/robGuderian','gaming.png',1,3,'critter',2,3,NULL);
INSERT INTO CARDS (name, image, playCost, rarity, type, damage, health, effectid) VALUES ('Maximum Power Rob','roids.png',3,4,'critter',4,10,NULL);
INSERT INTO PACKS (name, image) VALUES('Assorted Critters','pack0.png');
INSERT INTO PACKS (name, image) VALUES('Athletic Assailants','pack2.png');
INSERT INTO PACKS (name, image) VALUES('Power of the Sea','pack1.png');
INSERT INTO PACKS (name, image) VALUES('"Fair Use"','pack3.png');
INSERT INTO PACKS (name, image) VALUES('From the Far North','pack4.png');
INSERT INTO PACKS (name, image) VALUES('Into the Robverse','pack5.png');
INSERT INTO PACKCARDS VALUES(1,1);
INSERT INTO PACKCARDS VALUES(1,2);
INSERT INTO PACKCARDS VALUES(1,3);
INSERT INTO PACKCARDS VALUES(1,4);
INSERT INTO PACKCARDS VALUES(1,5);
INSERT INTO PACKCARDS VALUES(1,16);
INSERT INTO PACKCARDS VALUES(1,17);
INSERT INTO PACKCARDS VALUES(1,18);
INSERT INTO PACKCARDS VALUES(1,19);
INSERT INTO PACKCARDS VALUES(1,28);
INSERT INTO PACKCARDS VALUES(1,29);
INSERT INTO PACKCARDS VALUES(1,30);
INSERT INTO PACKCARDS VALUES(1,38);
INSERT INTO PACKCARDS VALUES(1,37);
INSERT INTO PACKCARDS VALUES(1,43);
INSERT INTO PACKCARDS VALUES(2,10);
INSERT INTO PACKCARDS VALUES(2,6);
INSERT INTO PACKCARDS VALUES(2,7);
INSERT INTO PACKCARDS VALUES(2,8);
INSERT INTO PACKCARDS VALUES(2,9);
INSERT INTO PACKCARDS VALUES(2,20);
INSERT INTO PACKCARDS VALUES(2,21);
INSERT INTO PACKCARDS VALUES(2,22);
INSERT INTO PACKCARDS VALUES(2,23);
INSERT INTO PACKCARDS VALUES(2,31);
INSERT INTO PACKCARDS VALUES(2,32);
INSERT INTO PACKCARDS VALUES(2,33);
INSERT INTO PACKCARDS VALUES(2,39);
INSERT INTO PACKCARDS VALUES(2,40);
INSERT INTO PACKCARDS VALUES(2,44);
INSERT INTO PACKCARDS VALUES(3,11);
INSERT INTO PACKCARDS VALUES(3,12);
INSERT INTO PACKCARDS VALUES(3,13);
INSERT INTO PACKCARDS VALUES(3,14);
INSERT INTO PACKCARDS VALUES(3,15);
INSERT INTO PACKCARDS VALUES(3,24);
INSERT INTO PACKCARDS VALUES(3,25);
INSERT INTO PACKCARDS VALUES(3,26);
INSERT INTO PACKCARDS VALUES(3,27);
INSERT INTO PACKCARDS VALUES(3,34);
INSERT INTO PACKCARDS VALUES(3,35);
INSERT INTO PACKCARDS VALUES(3,36);
INSERT INTO PACKCARDS VALUES(3,41);
INSERT INTO PACKCARDS VALUES(3,42);
INSERT INTO PACKCARDS VALUES(3,45);
INSERT INTO PACKCARDS VALUES(4,49);
INSERT INTO PACKCARDS VALUES(4,50);
INSERT INTO PACKCARDS VALUES(4,51);
INSERT INTO PACKCARDS VALUES(4,52);
INSERT INTO PACKCARDS VALUES(4,53);
INSERT INTO PACKCARDS VALUES(4,54);
INSERT INTO PACKCARDS VALUES(4,55);
INSERT INTO PACKCARDS VALUES(4,56);
INSERT INTO PACKCARDS VALUES(4,57);
INSERT INTO PACKCARDS VALUES(4,58);
INSERT INTO PACKCARDS VALUES(4,59);
INSERT INTO PACKCARDS VALUES(4,60);
INSERT INTO PACKCARDS VALUES(4,61);
INSERT INTO PACKCARDS VALUES(4,62);
INSERT INTO PACKCARDS VALUES(4,63);
INSERT INTO PACKCARDS VALUES(5,64);
INSERT INTO PACKCARDS VALUES(5,65);
INSERT INTO PACKCARDS VALUES(5,66);
INSERT INTO PACKCARDS VALUES(5,67);
INSERT INTO PACKCARDS VALUES(5,68);
INSERT INTO PACKCARDS VALUES(5,69);
INSERT INTO PACKCARDS VALUES(5,70);
INSERT INTO PACKCARDS VALUES(5,71);
INSERT INTO PACKCARDS VALUES(5,72);
INSERT INTO PACKCARDS VALUES(5,73);
INSERT INTO PACKCARDS VALUES(5,74);
INSERT INTO PACKCARDS VALUES(5,75);
INSERT INTO PACKCARDS VALUES(5,76);
INSERT INTO PACKCARDS VALUES(5,77);
INSERT INTO PACKCARDS VALUES(6,78);
INSERT INTO PACKCARDS VALUES(6,79);
INSERT INTO PACKCARDS VALUES(6,80);
INSERT INTO PACKCARDS VALUES(6,81);
INSERT INTO PACKCARDS VALUES(6,82);
INSERT INTO PACKCARDS VALUES(6,83);
INSERT INTO PACKCARDS VALUES(6,84);
INSERT INTO PACKCARDS VALUES(6,85);
INSERT INTO PACKCARDS VALUES(6,86);
INSERT INTO PACKCARDS VALUES(6,87);
INSERT INTO PACKCARDS VALUES(6,88);
INSERT INTO PACKCARDS VALUES(6,89);
INSERT INTO PACKCARDS VALUES(6,90);
INSERT INTO PACKCARDS VALUES(6,91);
INSERT INTO PACKCARDS VALUES(6,92);
INSERT INTO CARDSLOT VALUES(1,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(1,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(2,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(2,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(3,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(3,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(4,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(4,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(5,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(5,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO CARDSLOT VALUES(6,1,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,2,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,3,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,4,4.0e0,3.5e0,2.5e0,1.75e0,0.25e0);
INSERT INTO CARDSLOT VALUES(6,5,0e0,0e0,6.0e0,3.0e0,1.0e0);
INSERT INTO TRANSACTIONS (type) VALUES('m_card');
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONS (type) VALUES('m_bundle');
INSERT INTO TRANSACTIONS (type) VALUES('m_card');
INSERT INTO TRANSACTIONITEM VALUES(1,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'currency','0',NULL,NULL,15,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'currency','0',NULL,NULL,30,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'currency','0',NULL,NULL,0,1);
INSERT INTO TRANSACTIONITEM VALUES(4,'card','1',NULL,45,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(1,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(2,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(3,'card','1',NULL,2,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(5,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(5,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','0',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','0',NULL,44,NULL,1000);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,45,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(5,'card','1',NULL,46,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(6,'card','1',NULL,48,NULL,5);
INSERT INTO TRANSACTIONITEM VALUES(7,'card','1',NULL,48,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(8,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(8,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(9,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(9,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(10,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(10,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(11,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(11,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_pack');
INSERT INTO TRANSACTIONITEM VALUES(12,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(12,'pack','1',6,NULL,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('m_bundle');
INSERT INTO TRANSACTIONITEM VALUES(13,'currency','0',NULL,NULL,50,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',1,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',2,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',3,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',4,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',5,NULL,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(13,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(5,'Trader Norman','trader4');
INSERT INTO TRADEINFO VALUES(6,'Raccoon Dealer','trader1');
INSERT INTO TRADEINFO VALUES(7,'Wise Ratman','trader2');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,20,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,11,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'card','0',NULL,1,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(14,'pack','1',6,NULL,NULL,1);
INSERT INTO TRADEINFO VALUES(14,'Shady Alley Guy','trader7');
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(15,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','0',NULL,6,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(15,'card','1',NULL,24,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(16,'card','0',NULL,92,NULL,1);
INSERT INTO TRANSACTIONITEM VALUES(16,'currency','1',NULL,NULL,100,1);
INSERT INTO TRADEINFO VALUES(15,'Pawn Shop Owner','trader8');
INSERT INTO TRADEINFO VALUES(16,'Card Collector','trader6');
INSERT INTO TRANSACTIONS (type) VALUES( 'r');
INSERT INTO TRANSACTIONS (type) VALUES( 'r');
INSERT INTO TRANSACTIONITEM VALUES(17,'card','1',NULL,45,NULL,2);
INSERT INTO TRANSACTIONITEM VALUES(18,'currency','1',NULL,NULL,10,1);
INSERT INTO BATTLEINFO VALUES(1, 'Norman', 'Robs Grandpa', 'card_id_59', 17);
INSERT INTO BATTLEINFO VALUES(2, 'MARGIT, THE FELL OMEN', 'Someone must extinguish thy flame. Let it be Margit the Fell!', 'card_id_51', 18);
-- Vendors
INSERT INTO VENDORS (name, image, refresh) VALUES ('Roberto', 'image.png',3600);
INSERT INTO VENDORS (name, image, refresh) VALUES ('Sketch', 'image.png',3600);
INSERT INTO VENDORS (name, image, refresh) VALUES ('just some guy', 'image.png',3600);
INSERT INTO VENDORS (name, image, refresh) VALUES ('Dave', 'image.png',3600);

-- Roberto
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(19,'currency','0',NULL,NULL,0,1);
INSERT INTO TRANSACTIONITEM VALUES(19,'card','1',NULL,24,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 19, 0);
INSERT INTO StandardOffers Values(19);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(20,'currency','0',NULL,NULL,0,1);
INSERT INTO TRANSACTIONITEM VALUES(20,'card','1',NULL,5,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 20, 1);
INSERT INTO StandardOffers Values(20);
-- Money Printer
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES(2, 21, 0);
INSERT INTO StandardOffers Values(21);
INSERT INTO TRANSACTIONITEM VALUES(21,'currency','0',NULL,NULL,1,1);
INSERT INTO TRANSACTIONITEM VALUES(21,'currency','1',NULL,NULL,100,1);

-- Packs
INSERT INTO VENDOROFFERS VALUES (3,8,0);
INSERT INTO VENDOROFFERS VALUES (3,9,1);
INSERT INTO VENDOROFFERS VALUES (3,10,1);
INSERT INTO VENDOROFFERS VALUES (3,11,2);
INSERT INTO VENDOROFFERS VALUES (3,12,3);
INSERT INTO StandardOffers Values(8);
INSERT INTO StandardOffers Values(9);
INSERT INTO StandardOffers Values(10);
INSERT INTO StandardOffers Values(11);
INSERT INTO StandardOffers Values(12);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (3,22,4);
INSERT INTO StandardOffers Values(22);
INSERT INTO TRANSACTIONITEM VALUES(22,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(22,'card','0',NULL,24,NULL,3);
INSERT INTO TRANSACTIONITEM VALUES(22,'pack','1',6,NULL,NULL,3);
-- Rob Cards
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,23,3);
INSERT INTO StandardOffers Values(23);
INSERT INTO TRANSACTIONITEM VALUES(23,'currency','0',NULL,NULL,20,1);
INSERT INTO TRANSACTIONITEM VALUES(23,'card','1',NULL,48,NULL,1);
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,24,0);
INSERT INTO StandardOffers Values(24);
INSERT INTO TRANSACTIONITEM VALUES(24,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(24,'card','1',NULL,89,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,25,1);
INSERT INTO StandardOffers Values(25);
INSERT INTO TRANSACTIONITEM VALUES(25,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(25,'card','1',NULL,85,NULL,3);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,26,2);
INSERT INTO StandardOffers Values(26);
INSERT INTO TRANSACTIONITEM VALUES(26,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(26,'card','1',NULL,87,NULL,3);
INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,27,2);
INSERT INTO StandardOffers Values(27);
INSERT INTO TRANSACTIONITEM VALUES(27,'card','0',NULL,80,NULL,15);
INSERT INTO TRANSACTIONITEM VALUES(27,'card','1',NULL,92,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,28,1);
INSERT INTO SpecialOffers Values(28, true);
INSERT INTO TRANSACTIONITEM VALUES(28,'currency','0',NULL,NULL,14,1);
INSERT INTO TRANSACTIONITEM VALUES(28,'card','1',NULL,80,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES( 't');
INSERT INTO VENDOROFFERS VALUES (4,29,1);
INSERT INTO DiscountOffers Values(29, 28, 50);
INSERT INTO TRANSACTIONITEM VALUES(29,'currency','0',NULL,NULL,7,1);
INSERT INTO TRANSACTIONITEM VALUES(29,'card','1',NULL,80,NULL,1);

INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(30,'currency','0',NULL,NULL,10,1);
INSERT INTO TRANSACTIONITEM VALUES(30,'card','1',NULL,10,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 30, 0);
INSERT INTO StandardOffers Values(30);
INSERT INTO TRANSACTIONS (type) VALUES('t');
INSERT INTO TRANSACTIONITEM VALUES(31,'currency','0',NULL,NULL,5,1);
INSERT INTO TRANSACTIONITEM VALUES(31,'card','1',NULL,10,NULL,1);
INSERT INTO VENDOROFFERS VALUES (1, 31, 0);
INSERT INTO DiscountOffers Values(31,30,50);
